events {}

http {
    server {
        listen 80;

        # Serve your React build
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }

        # Expose Nginx stub_status for Prometheus exporter
        location /stub_status {
            stub_status;
            allow 127.0.0.1;   # allow localhost
            allow all;         # allow all (optional, for testing)
            deny all;          # deny others if you want stricter access
        }
    }
}
